### PR TITLE
[core] Exclude legacy components from the package

### PR DESCRIPTION
**Pull request by michaldudak**
- Included only a subset of components and hooks in the npm package - the ones we recently created (Checkbox, Number Field), the one we converted to the new API (Switch), hooks that are used by these components or will be used in the near future (useButton, useList) and utility functions.
- Removed the legacy components from the table of contents in the docs. The actual pages were not removed as we may reuse the content.

Preview: https://deploy-preview-288--base-ui.netlify.app/base-ui/all-components/

### CODE REVIEW

**Comment by colmtuite** [comment]
Checkbox is not listed on the "All Components" page. Also, we should wait to merge NumberField and include it in this release.

**Comment by michaldudak** [comment]
We're going to need images for the Checkbox and Number Field for the All Components page (cc @danilo-leal). This can be done in a separate PR, though.

**Review by atomiks — APPROVED** [review]
I think the utils need to be reworked quite a bit too — regarding naming, APIs, and edge cases unhandled. 

I'm wondering if utils should be excluded entirely for now?

**Comment by michaldudak** [comment]
OK, I'm fine with including just the new three components and their required hooks initially.

**Review by colmtuite — APPROVED** [review]

**Pull request merged**
