### PR TITLE
[core] Make callback parameters consistent

### PR DESCRIPTION
**Pull request by michaldudak**
- Renamed the first parameter to match the callback name (`value` in `onValueChange`, `checked` in `onCheckedChange`, etc.).
- Using native events in all public event handlers.
- Renamed `SliderRoot.onValueChange` second parameter to `activeThumbIndex` and moved it to the third position.

### CODE REVIEW

**Review by vladmoroz — APPROVED** [review]

**Review by vladmoroz — COMMENTED** [review]
Not seeing `docs/reference` changes, could this branch be based off an older commit?

**Comment by michaldudak** [comment]
No, it's from the lastest master. Is the `docs:api` script supposed to update these files?

**Comment by vladmoroz** [comment]
>No, it's from the lastest master. Is the docs:api script supposed to update these files?

Duh I realised it's not updated because there is an override on Slider's `onValueChange` type

image

Check `docs/reference/overrides/slider-root.json`

**Comment by michaldudak** [comment]
:/ that's an unfortunate consequence of having the definitions in several places. I hope we'll have time to do this properly soon.

**Comment by vladmoroz** [comment]
Yeah totally agree @michaldudak 
Will start getting a lot easier though when we don't have two sets of API data for the docs

**Pull request merged**
