### PR TITLE
[docs] Improve API reference copy

### PR DESCRIPTION
**Pull request by samuelsycamore**
"place its parts the following way" struck me as awkward phrasing—how about "assemble ~it as shown below~ its parts"?

### CODE REVIEW

**Comment by vladmoroz** [comment]
Actually crossed my mind the other day that this is more specific than it needs to be. Can we say something like "Import the component and put it together"? What I'm getting at is that in some cases, the order/composition matters a lot, and in some there is flexibility to it, so I don't want this to sound too prescriptive.

**Comment by mapache-salvaje** [comment]
Ah that's interesting @vladmoroz. Maybe something like "After importing the component, you can render the following DOM nodes (or subcomponents, or elements, have you settled on a common term for these pieces?):"? This would convey the idea that you have options rather than a strict prescription of what must be included.

**Comment by vladmoroz** [comment]
Hmm I think we need to keep it a bit ambiguous so it works regardless whether there is some or absolutely no flexibility to the anatomy. "You can render the following DOM nodes..." sounds like there always are options.

How about `Import the component and assemble its parts`? (To your question, those pieces are called "parts")

**Comment by mapache-salvaje** [comment]
Makes sense, I'll run with that 🫡

**Review by vladmoroz — APPROVED** [review]

**Pull request merged**
