### PR TITLE
[useAnchorPositioning] Fix `transform-origin` calculation

### PR DESCRIPTION
**Pull request by atomiks**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/base-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

**Comment by michaldudak** [comment]
What was the issue about?

**Comment by atomiks** [comment]
Calculation was incorrect with `sideOffset`, it didn't emanate from the center of the anchor or arrow tip.

**Comment by mnajdova** [comment]
Can you please screenshot the prevkious & current behavior? It's hard to review at least for me without more context.

**Comment by atomiks** [comment]
Experiment here: https://deploy-preview-986--base-ui.netlify.app/experiments/popup-transform-origin

Before (incorrect `sideOffset` calc):
https://github.com/user-attachments/assets/bcaf000a-63cc-4609-b80b-4bfdc5d50190

After:
https://github.com/user-attachments/assets/470d0600-347e-4ce9-9d31-048ef645a45b

**Review by michaldudak — APPROVED** [review]

**Pull request merged**
