### PR TITLE
[docs] Fix API info generation for Menu.* and Tabs.* components

### PR DESCRIPTION
**Pull request by mnajdova**
Preview: https://deploy-preview-964--base-ui.netlify.app/new/components/menu#submenu-trigger

Renamed the following components:
- SubmenuTrigger -> MenuSubmenuTrigger
- Tab -> TabsTab
- TabIndicator -> TabsTabIndicator
- TabPanel -> TabsTabPanel

### CODE REVIEW

**Comment by michaldudak** [comment]
Do you know what is the root cause of the issue? Why did the docgen ignore the component with its previous name?

**Comment by mnajdova** [comment]
The logic comes from here: https://github.com/mui/base-ui/blob/master/docs/src/components/reference/rehypeReference.mjs#L52 it expects that each part starts with the component name. I noticed that only this component didn't follow this pattern, so I renamed it.

**Comment by michaldudak** [comment]
It's also the case with Tabs (we don't have TabsTab, just Tab)

**Comment by mnajdova** [comment]
NIce catch, I guess Vlad didn't get to the Tabs doc yet :) I will fix it as part of this PR too.

**Review by vladmoroz — APPROVED** [review]

**Pull request merged**
