### PR TITLE
[docs] Nested dialog demo

### PR DESCRIPTION
**Pull request by vladmoroz**
- Nested dialog demo
- Remove quick nav pointer events auto

https://deploy-preview-1146--base-ui.netlify.app/react/components/dialog

### CODE REVIEW

**Review by colmtuite — APPROVED** [review]

**Comment by michaldudak** [comment]
IMO nested menus would look better if they were slightly more apart. The double border between them doesn't look pretty.

image

**Comment by vladmoroz** [comment]
Good spot @michaldudak 

Probably will do this though

image

**Comment by michaldudak** [comment]
Looks great as well!

**Comment by michaldudak** [comment]
Something is broken on iOS - when the nested trigger is clicked the whole menu closes immediately.

**Comment by vladmoroz** [comment]
Yeah I saw it @michaldudak—don't think it's at the example level

**Pull request merged**
