### PR TITLE
[docs] Add menu demos

### PR DESCRIPTION
**Pull request by vladmoroz**
- Add code block line highlights
- Add menu checkbox items demo
  - Note: check icon isn't unmounted yet, I'll create an issue
- Add menu open on hover demo
- Add menu with submenu demo

### CODE REVIEW

**Comment by colmtuite** [comment]
@vladmoroz Checkbox items demo is not working. Why is the nested menu demo split into two separate code blocks?

**Comment by vladmoroz** [comment]
> Checkbox items demo is not working

https://github.com/mui/base-ui/issues/1121

**Comment by vladmoroz** [comment]
> Why is the nested menu demo split into two separate code blocks?

I think it's important to show a high-level overview of the submenu anatomy first so it's easy to understand how it's composed before looking at the detailed demo

Also have just updated the example demos to use a more compact view—how do you feel about this altogether?
https://deploy-preview-1120--base-ui.netlify.app/react/components/menu

**Review by mnajdova — CHANGES_REQUESTED** [review]
When choosing a menu item from the hover example, it scrolls to the top of the page.
Checkbox item demo is still not working (probably we just need to rebase with master, as https://github.com/mui/base-ui/issues/1121 is fixed)

**Comment by michaldudak** [comment]
The checkboxitems demo should have the positioner/portal always mounted so the checked state is remembered when the menu is closed.

**Comment by vladmoroz** [comment]
> The checkboxitems demo should have the positioner/portal always mounted so the checked state is remembered when the menu is closed.

Hmm probably a more realistic example would be to show controlled demos instead of keeping stuff mounted

**Comment by atomiks** [comment]
The submenu demo right at the bottom feels awkward because it's near the bottom of the screen, feels like there should be more breathing room below it

**Comment by vladmoroz** [comment]
> The submenu demo right at the bottom feels awkward because it's near the bottom of the screen, feels like there should be more breathing room below it

Agree it's awkward

I think it just needs a logical way to the next page, like next/prev component links.

Adding more space makes it more awkward too.

**Comment by vladmoroz** [comment]
Updates:
- Added radio items
- Made radio and checkbox items controlled
- Added a menu item + link example
- Added a `closeOnClick` example
- Added an example with group labels

@mnajdova the bugs are gone after merging with master

**Review by mnajdova — APPROVED** [review]
Demos look good. I noticed an issue with the table of content (it jumps when you open a menu). We can fixed it separately


https://github.com/user-attachments/assets/c0e48065-7e30-498d-bb5b-88a7ea03c018

**Pull request merged**
