### PR TITLE
[Collapsible] Make parameters in useCollapsilbe*  hooks mandatory 

### PR DESCRIPTION
**Pull request by sai6855**
Part of https://github.com/mui/base-ui/issues/856

Collapsible docs: https://deploy-preview-752--base-ui.netlify.app/components/react-collapsible/

### CODE REVIEW

**Comment by michaldudak** [comment]
The default values are set in the hook. We can make it consistent and set everything on the component, though. In this case, I'd recommend making the hook parameters mandatory.

**Comment by mj12albert** [comment]
> We can make it consistent and set everything on the component, though. In this case, I'd recommend making the hook parameters mandatory.

@sai6855 Thanks for working on this 🙏 we discussed this and decided to generally assign default values to optional props in the component, and have hook params be required: https://github.com/mui/base-ui/issues/856

**Comment by michaldudak** [comment]
@sai6855, if you could make the parameters in the hook mandatory, we can merge this PR.

**Comment by sai6855** [comment]
> @sai6855, if you could make the parameters in the hook mandatory, we can merge this PR.

Got it, I'll make the changes. Some how i missed this notification

**Comment by sai6855** [comment]
@michaldudak @mj12albert PR is ready for review

**Comment by mj12albert** [comment]
@sai6855 Apologies, I folded all the changes into https://github.com/mui/base-ui/pull/889
Thanks for spending the time 🙇

**Pull request closed without merging**
