### PR TITLE
[core] Copy supporting files from the Core repository

### PR DESCRIPTION
**Pull request by michaldudak**
Copied all the files needed to run the docs site, tests, and supporting scripts.

The docs contain only the Base UI pages. All the others were removed. There may still be several unused components there.

Where possible, infra packages are referenced through npm. One notable exception is api-docs-builder, which hasn't been converted to a package yet. It is referenced through the Git repo (similarly to how it's done in MUI X and Toolpad).

Some of the scripts and config files use the Core monorepo Git dependency as well.

### CODE REVIEW

**Comment by colmtuite** [comment]
I just noticed the following that we chatted about:

- Marketing site is unfinished with broken buttons/links
- Interactive component demos don't work
- Docs sidebar accordion menus are missing animation/transition 
- Docs header product switcher is broken

**Comment by michaldudak** [comment]
The Netlify redirects were not set up correctly. It should work well now.

**Comment by mnajdova** [comment]
Is it intentional that the docs "Base UI" link looks like this?
Screenshot 2024-02-27 at 14 01 15

Some images are broken, e.g.
https://deploy-preview-6--base-ui.netlify.app/base-ui/getting-started/support/#bug-reproductions

Screenshot 2024-02-27 at 14 03 53

I can't finish reviewing later today.

**Comment by michaldudak** [comment]
The link looks the same as on the Material UI site: https://mui.com/base-ui/. As we are in the Base UI section, the link is highlighted.

As a side note, I don't think we'll replace the Base UI subsite on mui.com with these docs anytime soon. I'd wait until we have a consistent API across all components and then release a package and new docs. For now, we'll be able to access it via https://master--base-ui.netlify.com

---

I fixed the broken images.

**Comment by colmtuite** [comment]
All header navigation links are broken except Base UI. Everything else seems ok so far.

**Comment by michaldudak** [comment]
That's kind of expected (and consistent with how previews of other subsites like MUI X work). Links will work when the site is integrated into the MUI site.

**Review by colmtuite — APPROVED** [review]

**Pull request merged**
